using System.Text;
using Unitz.Core.Generators.Helpers;
using Unitz.Core.Generators.Models;

namespace Unitz.Core.Generators.Emitting;

internal abstract class BaseSourceEmitter : ISourceEmitter
{
    public string Generate(QuantityModel model)
    {
        var stringBuilder = new StringBuilder();
        var codeWriter = new CodeWriter(stringBuilder);
        codeWriter.WriteLine("// <auto-generated />");
        codeWriter.WriteLine("#nullable enable");
        codeWriter.WriteLine("#pragma warning disable CS1591");
        codeWriter.WriteLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            codeWriter.WriteLine($"namespace {model.Namespace};");
        }

        GenerateSource(codeWriter, model);
    
        return stringBuilder.ToString();
    }

    public abstract string GetTypeName(QuantityModel model);

    protected abstract void GenerateSource(CodeWriter codeWriter, QuantityModel model);
}
